#Declare Environment Variable

#Target Operation

.PHONY: all

all: graph_struct.c

check_opdir: all

	if [ -d "./bin" ]; then\
	    echo "Dir exists";\
	else\
	    echo "Dir not exist!"\
	fi
clean:
	rm *.o

